# Generated by Django 5.1.3 on 2024-12-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0003_alter_mandate_mandate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='mandate_image',
            field=models.ImageField(null=True, upload_to='mandate/images/mandate/'),
        ),
    ]
