# Generated by Django 5.1.3 on 2024-12-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0004_mandate_confirmation_alter_mandate_mandate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='credit_account',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
