# Generated by Django 5.1.3 on 2024-12-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0005_mandate_credit_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='credit_account',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='fixed_or_max',
            field=models.CharField(choices=[('F', 'Fixed'), ('M', 'Max Amount')], default='F', max_length=1),
        ),
    ]
