# Generated by Django 5.1.3 on 2024-12-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0006_alter_mandate_credit_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='message_reference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
