# Generated by Django 5.1.3 on 2024-12-09 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0007_alter_mandate_message_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mandate.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='credit_account',
            field=models.CharField(max_length=100, verbose_name='Credit Account'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='creditor_bank',
            field=models.CharField(default='SARVA HARYANA GRAMIN BANK', max_length=300, verbose_name='Creditor Bank'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='creditor_name',
            field=models.CharField(max_length=300, verbose_name='Creditor Name'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='creditor_utility_code',
            field=models.CharField(default='HGBX00002000017848', max_length=100, verbose_name='Creditor Utility Code'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='currency',
            field=models.CharField(max_length=5, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='date_of_mandate',
            field=models.DateField(verbose_name='Date of Mandate'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='debtor_acc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mandate.debtoracctype', verbose_name='Debtor Account Type'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='debtor_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mandate.debtorbank', verbose_name='Debtor Bank'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='debtor_legal_account_number',
            field=models.CharField(max_length=100, verbose_name='Debtor Legal Account Number'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='fixed_or_max',
            field=models.CharField(choices=[('F', 'Fixed'), ('M', 'Max Amount')], default='F', max_length=1, verbose_name='Amount Type'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mandate.frequency', verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='mandate_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Mandate File'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='mandate_image',
            field=models.ImageField(null=True, upload_to='mandate/images/mandate/', verbose_name='Mandate Image'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='message_reference',
            field=models.CharField(max_length=100, null=True, verbose_name='Message Reference'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='name_of_debtor_account_holder',
            field=models.CharField(max_length=300, verbose_name='Name of Debor Account Holder'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='umrn',
            field=models.CharField(max_length=50, verbose_name='UMRN'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mandate.variant', verbose_name='Variant'),
        ),
    ]
