# Generated by Django 5.1.3 on 2024-12-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0008_alter_mandate_amount_alter_mandate_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='currency',
            field=models.CharField(default='INR', max_length=5, verbose_name='Currency'),
        ),
    ]
