# Generated by Django 5.1.3 on 2025-01-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0009_alter_mandate_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='response_npci',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='status_npci',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mandate',
            name='uploaded_npci',
            field=models.BooleanField(default=False),
        ),
    ]
