# Generated by Django 4.2.17 on 2025-01-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0010_mandate_response_npci_mandate_status_npci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='debtor_account_number_ifsc',
            field=models.CharField(default='PUNB0HGB001', max_length=11, verbose_name='Debtor Account IFSC'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='fixed_or_max',
            field=models.CharField(choices=[('F', 'Fixed'), ('M', 'Max')], default='F', max_length=1, verbose_name='Amount Type'),
        ),
    ]
