# Generated by Django 4.2.17 on 2025-01-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0011_mandate_debtor_account_number_ifsc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='debtor_account_number_ifsc',
            field=models.CharField(max_length=11, verbose_name='Debtor Account IFSC'),
        ),
    ]
