# Generated by Django 4.2.17 on 2025-01-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0012_alter_mandate_debtor_account_number_ifsc'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mandate',
            constraint=models.CheckConstraint(check=models.Q(('start_date__gte', models.F('date_of_mandate'))), name='startDate_gte_dateOfMandate', violation_error_message='Start Date can not be before Date of Mandate'),
        ),
    ]
