# Generated by Django 5.1.5 on 2025-02-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0013_mandate_startdate_gte_dateofmandate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandate',
            name='variant',
        ),
        migrations.RemoveConstraint(
            model_name='mandate',
            name='startDate_gte_dateOfMandate',
        ),
        migrations.AlterField(
            model_name='mandate',
            name='credit_account',
            field=models.CharField(help_text='The loan/other account in SHGB in which the installment is to be credited.', max_length=100, verbose_name='Credit Account'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='end_date',
            field=models.DateField(help_text='The end date can not be beyond 40 years after start date ', verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='name_of_debtor_account_holder',
            field=models.CharField(help_text='The name as per the debit account.', max_length=300, verbose_name='Name of Debor Account Holder'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='start_date',
            field=models.DateField(help_text='The start date should be on or after the date of mandate.', verbose_name='Start Date'),
        ),
        migrations.AddConstraint(
            model_name='mandate',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__gte', models.F('date_of_mandate'))), name='startDate_gte_dateOfMandate', violation_error_message='"Start Date" can not be before the "Date of Mandate"'),
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
