# Generated by Django 5.1.5 on 2025-02-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0014_remove_mandate_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='fixed_or_max',
            field=models.CharField(choices=[('F', 'Fixed Amount'), ('M', 'Max Amount')], max_length=1, verbose_name='Amount Type'),
        ),
    ]
