# Generated by Django 5.1.5 on 2025-02-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0016_alter_mandate_fixed_or_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='fixed_or_max',
            field=models.CharField(choices=[(None, ''), ('F', 'Fixed Amount'), ('M', 'Max Amount')], max_length=1, verbose_name='Debit Type'),
        ),
    ]
