# Generated by Django 5.1.5 on 2025-02-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0017_alter_mandate_fixed_or_max'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mandate',
            old_name='message_reference',
            new_name='ref',
        ),
    ]
