# Generated by Django 5.1.5 on 2025-02-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0018_rename_message_reference_mandate_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mandate',
            old_name='fixed_or_max',
            new_name='debit_type',
        ),
    ]
