# Generated by Django 5.1.5 on 2025-02-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0019_rename_fixed_or_max_mandate_debit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mandate',
            old_name='date_of_mandate',
            new_name='date',
        ),
    ]
