# Generated by Django 5.1.5 on 2025-02-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0020_rename_date_of_mandate_mandate_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mandate',
            name='startDate_gte_dateOfMandate',
        ),
        migrations.AddConstraint(
            model_name='mandate',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__gte', models.F('date'))), name='startDate_gte_date', violation_error_message='"Start Date" can not be before the "Date of Mandate"'),
        ),
    ]
