# Generated by Django 5.1.5 on 2025-02-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0021_remove_mandate_startdate_gte_dateofmandate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mandate',
            old_name='debtor_legal_account_number',
            new_name='debtor_acc_no',
        ),
        migrations.RenameField(
            model_name='mandate',
            old_name='name_of_debtor_account_holder',
            new_name='debtor_name',
        ),
    ]
