# Generated by Django 5.1.5 on 2025-02-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0022_rename_debtor_legal_account_number_mandate_debtor_acc_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mandate',
            old_name='debtor_account_number_ifsc',
            new_name='debtor_acc_ifsc',
        ),
    ]
