# Generated by Django 5.1.5 on 2025-02-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0023_rename_debtor_account_number_ifsc_mandate_debtor_acc_ifsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='category',
            field=models.CharField(default='L001', max_length=4, verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
