# Generated by Django 5.1.5 on 2025-02-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0024_alter_mandate_category_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
