# Generated by Django 5.1.5 on 2025-02-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0025_delete_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='debtor_acc_type',
            field=models.CharField(choices=[(None, ''), ('SAVINGS', 'SAVINGS'), ('CURRENT', 'CURRENT'), ('CC', 'CC'), ('Other', 'Other')], max_length=10, verbose_name='Debtor Account Type'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='frequency',
            field=models.CharField(choices=[(None, ''), ('ADHO', 'As and when presented'), ('INDA', 'Intra Day'), ('DAIL', 'Daily'), ('WEEK', 'Weekly'), ('BIMN', 'Bi-Monthly'), ('MNTH', 'Monthly '), ('QURT', 'Quaterly'), ('MIAN', 'Semi annually'), ('YEAR', 'Yearly'), ('BIMN', 'Bi-Monthly')], max_length=4, verbose_name='Frequency'),
        ),
        migrations.DeleteModel(
            name='DebtorAccType',
        ),
        migrations.DeleteModel(
            name='Frequency',
        ),
    ]
