# Generated by Django 5.1.5 on 2025-02-07 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0026_alter_mandate_debtor_acc_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mandate',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='confirmation',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='image_uploaded',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='response_npci',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='status_npci',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='umrn',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='uploaded_npci',
        ),
        migrations.AddField(
            model_name='mandate',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mandate',
            name='lm_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='seq_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mandate',
            name='submit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
