# Generated by Django 5.1.5 on 2025-02-07 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0027_alter_mandate_options_remove_mandate_confirmation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='submit_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create', to=settings.AUTH_USER_MODEL),
        ),
    ]
