# Generated by Django 5.1.5 on 2025-02-07 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0028_mandate_submit_user_alter_mandate_create_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seq_no', models.IntegerField()),
                ('npci_username', models.CharField(default='HGBX344857', max_length=35)),
                ('filename', models.CharField(max_length=35, null=True)),
            ],
            options={
                'ordering': ['date', 'seq_no'],
                'constraints': [models.UniqueConstraint(fields=('date', 'seq_no'), name='zip_date_seq_unique')],
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seq_no', models.IntegerField()),
                ('npci_username', models.CharField(default='HGBX344857', max_length=35)),
                ('npci_MsgId', models.CharField(max_length=35)),
                ('filename_prefix', models.CharField(max_length=35, null=True)),
                ('npci_upload_time', models.DateTimeField(null=True)),
                ('npci_umrn', models.CharField(max_length=35, null=True)),
                ('npci_status', models.CharField(max_length=35, null=True)),
                ('npci_reason_code', models.CharField(max_length=10, null=True)),
                ('npci_response_time', models.DateTimeField(null=True)),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mandate.mandate')),
            ],
            options={
                'ordering': ['date', 'seq_no'],
                'constraints': [models.UniqueConstraint(fields=('date', 'seq_no'), name='presentation_date_seq_unique')],
            },
        ),
    ]
