# Generated by Django 5.1.5 on 2025-02-07 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0030_presentation_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='zip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mandate.zip'),
        ),
    ]
