# Generated by Django 5.1.5 on 2025-02-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0031_alter_presentation_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='debtor_joint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mandate',
            name='debtor_name_2',
            field=models.CharField(help_text='The name as per the debit account.', max_length=300, null=True, verbose_name='Name of Debor Account Holder'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='debtor_name_3',
            field=models.CharField(help_text='The name as per the debit account.', max_length=300, null=True, verbose_name='Name of Debor Account Holder'),
        ),
    ]
