# Generated by Django 5.1.5 on 2025-02-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0032_mandate_debtor_joint_mandate_debtor_name_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='debtor_joint',
            field=models.BooleanField(default=False, help_text='Select this if the debtor account requires signature of multiple persons', verbose_name='Is the Debtor Account jointly held?'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='debtor_name_2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name of Debor Account Holder 2'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='debtor_name_3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name of Debor Account Holder 3'),
        ),
    ]
