# Generated by Django 5.1.5 on 2025-02-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0033_alter_mandate_debtor_joint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='debtor_joint',
            field=models.BooleanField(default=False, help_text='Select this if the debtor account requires signatures of multiple persons', verbose_name='Is the Debtor Account jointly held?'),
        ),
    ]
