# Generated by Django 5.1.5 on 2025-02-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0034_alter_mandate_debtor_joint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='debtor_name_2',
            field=models.CharField(blank=True, help_text='Mandatory', max_length=300, null=True, verbose_name='Name of Debor Account Holder 2'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='debtor_name_3',
            field=models.CharField(blank=True, help_text='Optional', max_length=300, null=True, verbose_name='Name of Debor Account Holder 3'),
        ),
    ]
