# Generated by Django 5.1.5 on 2025-02-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0035_alter_mandate_debtor_name_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='debtor_name_2',
            field=models.CharField(blank=True, help_text='Mandatory. At least one additional name required for joint account.', max_length=300, null=True, verbose_name='Name of Debor Account Holder 2'),
        ),
    ]
