# Generated by Django 5.1.5 on 2025-02-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0036_alter_mandate_debtor_name_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='npci_upload_error',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='frequency',
            field=models.CharField(choices=[(None, ''), ('ADHO', 'As and when presented'), ('INDA', 'Intra Day'), ('DAIL', 'Daily'), ('WEEK', 'Weekly'), ('BIMN', 'Bi-Monthly'), ('MNTH', 'Monthly '), ('QURT', 'Quaterly'), ('MIAN', 'Semi annually'), ('YEAR', 'Yearly')], max_length=4, verbose_name='Frequency'),
        ),
    ]
