# Generated by Django 5.1.5 on 2025-02-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0039_alter_mandate_email_alter_mandate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Installment Amount'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='debtor_name_2',
            field=models.CharField(blank=True, help_text='At least one additional name required for joint account.', max_length=300, null=True, verbose_name='Name of Debor Account Holder 2'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='debtor_name_3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name of Debor Account Holder 3'),
        ),
    ]
