# Generated by Django 5.1.5 on 2025-02-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0040_alter_mandate_amount_alter_mandate_debtor_name_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='ref',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
