# Generated by Django 5.1.5 on 2025-02-14 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0041_mandate_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='mandate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandate.mandate'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='zip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandate.zip'),
        ),
    ]
