# Generated by Django 5.1.5 on 2025-02-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0042_alter_presentation_mandate_alter_presentation_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='ref',
            field=models.CharField(max_length=35),
        ),
    ]
