# Generated by Django 5.1.5 on 2025-02-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0044_mandate_debit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='debit_date',
            field=models.CharField(choices=[(None, ''), ('3', '3rd day of month'), ('11', '11th day of month'), ('19', '19th day of month'), ('26', '26th day of month')], max_length=2, verbose_name='Date of EMI Collection'),
        ),
    ]
