# Generated by Django 5.1.3 on 2025-02-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0045_alter_mandate_debit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BO', 'Branch'), ('RO', 'Regional Office'), ('HO', 'Head Office')], max_length=2)),
                ('region', models.CharField(max_length=50, null=True)),
                ('sol_id', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=350)),
            ],
        ),
    ]
