# Generated by Django 5.1.3 on 2025-02-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0046_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.UniqueConstraint(fields=('sol_id',), name='office_sol_unique'),
        ),
    ]
