# Generated by Django 5.1.3 on 2025-02-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0047_alter_office_region_office_office_sol_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='region',
            field=models.CharField(blank=True, choices=[('AMB', 'Ambala'), ('BHI', 'Bhiwani'), ('FTH', 'Fatehbad'), ('GGN', 'Gurgaon'), ('HIS', 'Hisar'), ('KTL', 'Kaithal'), ('MDG', 'Mahendergarh'), ('NUH', 'Nuh'), ('PPT', 'Panipat'), ('RWR', 'Rewari'), ('RTK', 'Rohtak')], max_length=50, null=True),
        ),
    ]
