# Generated by Django 5.1.3 on 2025-02-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0048_alter_office_region'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='office',
            constraint=models.CheckConstraint(condition=models.Q(('type__exact', 'HO'), ('region__isnull', False), _connector='OR'), name='region_mandatory', violation_error_message='Please select a region name.'),
        ),
    ]
