# Generated by Django 5.1.3 on 2025-02-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0049_office_region_mandatory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandate',
            name='mandate_file',
        ),
    ]
