# Generated by Django 5.1.3 on 2025-02-15 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0050_remove_mandate_mandate_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mandate',
            constraint=models.UniqueConstraint(fields=('ref',), name='mandate_ref_unique'),
        ),
    ]
