# Generated by Django 5.1.5 on 2025-02-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0051_mandate_mandate_ref_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtorbank',
            options={'ordering': ['name']},
        ),
    ]
