# Generated by Django 5.1.5 on 2025-02-17 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0052_alter_debtorbank_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mandate.office'),
        ),
    ]
