# Generated by Django 5.1.5 on 2025-02-17 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0053_mandate_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mandate.office'),
            preserve_default=False,
        ),
    ]
