# Generated by Django 5.1.5 on 2025-02-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0054_alter_mandate_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mandate',
            old_name='branch',
            new_name='office',
        ),
    ]
