# Generated by Django 5.1.5 on 2025-02-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0058_alter_presentation_options_alter_zip_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='filename_prefix',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zip',
            name='filename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
