# Generated by Django 5.1.5 on 2025-02-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0060_alter_mandate_options_mandate_init_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='init_req_time',
            field=models.DateTimeField(null=True),
        ),
    ]
