# Generated by Django 5.1.5 on 2025-02-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0062_mandate_last_init_req_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='init_req_flag',
            field=models.BooleanField(default=False),
        ),
    ]
