# Generated by Django 5.2 on 2025-04-26 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0064_remove_mandate_init_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='debit_date',
            field=models.CharField(choices=[(None, 'Select EMI collection date'), ('3', '3rd day of month'), ('11', '11th day of month'), ('19', '19th day of month'), ('26', '26th day of month')], max_length=2, verbose_name='Date of EMI Collection'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='debtor_acc_no',
            field=models.CharField(max_length=100, verbose_name='Debtor Account Number'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='debtor_acc_type',
            field=models.CharField(choices=[(None, 'Select an account type'), ('SAVINGS', 'SAVINGS'), ('CURRENT', 'CURRENT'), ('CC', 'CC'), ('Other', 'Other')], max_length=10, verbose_name='Debtor Account Type'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='debtor_name',
            field=models.CharField(help_text='The name as per the debit account.', max_length=300, verbose_name='Debtor Name'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='debtor_name_2',
            field=models.CharField(blank=True, help_text='At least one additional name required for joint account.', max_length=300, null=True, verbose_name='Debtor Name 2'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='debtor_name_3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Debtor Name 3'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mandate.office', verbose_name='Branch'),
        ),
    ]
