# Generated by Django 5.1.5 on 2025-07-19 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0065_alter_mandate_debit_date_alter_mandate_debtor_acc_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='delete_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='delete_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delete', to=settings.AUTH_USER_MODEL),
        ),
    ]
