# Generated by Django 5.1.5 on 2025-07-21 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0066_mandate_delete_time_mandate_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='cancel_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cancel_req_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cancel_req_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cancel_req_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancel_req', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cancel_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cancel_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancel', to=settings.AUTH_USER_MODEL),
        ),
    ]
